APPLY_FIXES: none
DEFAULT_BRANCH: main
LINTER_RULES_PATH: ".github/linters"
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - CREDENTIALS_SECRETLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - ENV_DOTENV_LINTER
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SPELL_CSPELL
ENV_DOTENV_LINTER_FILE_NAMES_REGEX: [".env", ".env.sample"]
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "LICENSE.md"
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
SPELL_CSPELL_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: true
FILEIO_REPORTER: false
PRINT_ALPACA: false
VALIDATE_ALL_CODEBASE: true
