version: "3"
services:
  find-duplicates:
    image: jfandy1982/find-duplicates:latest
    volumes:
      - /volume1/austausch:/findup_data01:ro
      - /volume1/daten:/findup_data02:ro
      - /volume1/homes:/findup_data03:ro
      - /volume1/music:/findup_data04:ro
      - /volume1/photo:/findup_data05:ro
      - /volume1/docker/findduplicates/result:/findup_result
      - /volume1/docker/findduplicates/config:/findup_config
