name: Deployment Pipeline

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths-ignore:
  #   - '**.md'
  #   - '**.*ignore'
  #   - 'docs/**'
  #   - '.github/workflows/retention_period.yml'
  #   - '.github/workflows/update_dockerhub_description.yml'
  #   - '.github/dependabot.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  deploy:
    name: DockerHub Deployment

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
