name: Continous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build artifacts and run the test suite

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: build
        with:
          filters: |
            build_sources:
              - './scripts/**'

  lint:
    name: Check linting settings

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: "Execute checks in `MegaLinter`"
        uses: oxsecurity/megalinter/flavors/javascript@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MegaLinter Reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log

  docker-image-deploy:
    name: Deploy new docker image version to Docker Hub Repository

    runs-on: ubuntu-latest

    needs: lint

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: docker_image_deploy
        with:
          filters: |
            docker_image_rebuild:
              - './scripts/**'
              - added|modified: './Dockerfile'

      - name: Update Docker Image

        if: ${{ steps.docker_image_deploy.outputs.docker_image_rebuild == 'true' }}

        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  docker-sync-readme:
    name: Update README.md in Docker Hub Repository

    runs-on: ubuntu-latest

    needs: lint

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: docker_sync_readme
        with:
          filters: |
            docker_readme:
              - added|modified: './docs/docker/docker.md'

      - name: Sync README.md from file ./docs/docker/docker.md

        if: ${{ steps.docker_sync_readme.outputs.docker_readme == 'true' }}

        uses: meeDamian/sync-readme@v1.0.6
        with:
          readme: ./docs/docker/docker.md
          slug: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_PASSWORD }}
