name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - gh-pages

permissions:
  actions: read
  attestations: read
  checks: read
  contents: read
  deployments: read
  id-token: none
  issues: write
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  build:
    name: 'Build'

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Detect changes'
        uses: dorny/paths-filter@v3.0.2
        id: build
        with:
          filters: |
            build_sources:
              - './scripts/**'

  docker-image-deploy:
    name: Deploy new docker image version to Docker Hub Repository

    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v3.0.2
        id: docker_image_deploy
        with:
          filters: |
            docker_image_rebuild:
              - './scripts/**'
              - added|modified: './Dockerfile'

      - name: Update Docker Image

        if: ${{ steps.docker_image_deploy.outputs.docker_image_rebuild == 'true' }}

        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  docker-sync-readme:
    name: Update README.md in Docker Hub Repository

    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v3.0.2
        id: docker_sync_readme
        with:
          filters: |
            docker_readme:
              - added|modified: './docs/docker/docker.md'

      - name: Sync README.md from file ./docs/docker/docker.md

        if: ${{ steps.docker_sync_readme.outputs.docker_readme == 'true' }}

        uses: meeDamian/sync-readme@v1.0.6
        with:
          readme: ./docs/docker/docker.md
          slug: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_PASSWORD }}
